-- 데이터 출처: 식품의약품안전처 조리식품의 레시피 DB (COOKRCP01), 공공누리 1유형
-- 생성: scripts/etl/load/sql_writer.py
-- recipe_id >= 11 은 실데이터 (1~10는 시연 더미 보존)

USE smart_fridge;
-- 신규 재료 마스터 (손유경 검토 후 적용)

INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('칵테일새우', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('생크림', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('날콩가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('방울토마토', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('멸치액젓', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('매실액', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('물', 1, 'ml');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('통깨 약간', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오이', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진 땅콩', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('사과', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('딸기', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('플레인요거트', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('메추리알', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('블루베리', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('대추', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('배', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('애호박', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('단호박', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('인삼', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('양송이', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('저염간', 1, '장');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('후춧가루', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다시마', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('건새우', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('비트', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('치자가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('겨자가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('식초', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파슬리', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레디쉬', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('150g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('로즈', 1, '마리');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오렌지', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새송이버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('땅콩', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('올리브오일', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('유자청', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('전복', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새우', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레몬', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('녹말', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('식용꽃', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('참나물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('토마토', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('어린잎', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오징어', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('미니파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홍고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('올리고당', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('꽈리고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('샐러리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('화이트와인', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홀토마토', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파슬리가루', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('삼치', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('로즈마리', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레몬즙', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('귀리밥', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아욱', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('전분가루', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('팽이버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진돼지고기', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('정종', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('주꾸미', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청경채', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('녹말가루', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아몬드', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('호두', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('코코넛밀크', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('브로컬리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('카레가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('쌀', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('강황가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새송이', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('닭고기살', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('튀김기름', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('함초가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진 돼지고기', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진 소고기', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('빵가루', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('- 곁들임채소 : 어린잎(5g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('느타리버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('흑임자', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('견과류', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('연근', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('천일염', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('계피가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('돼지고기(안심', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('100g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('도라지', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청포묵', 7, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('라이스페이퍼', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('콜라비', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('피망', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('쪽파', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('표고버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('찹쌀가루', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('닭다리살', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('들깻가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('브로콜리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('송송 썬 붉은 고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새싹채소', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('만두피', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('올리브유', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('꿀', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아스파라거스', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('플레인 요구르트', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('어린잎채소', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레드와인', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('매실청', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진 파', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청양고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('조기', 4, '마리');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('전분', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('밥', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('노란파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('밤', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('콩나물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('함초', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('연겨자', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('마요네즈', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('참깨', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('참외', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('연어', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('말린 토마토', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바나나', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('잣', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('들기름', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('들깨가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('요거트', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('연유', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('누룽지', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('양배추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홍파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('노랑파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('적양배추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('생선살', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('가지', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('현미쌀', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('조', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('달걀흰자', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('물녹말(녹말가루', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('물 10g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새싹', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('닭고기(가슴살', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('양송이버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('날치알', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('120g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('더덕', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파인애플', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('찹쌀', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소고기(홍두깨살', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('두릅', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아보카도', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('두유', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('우엉', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('문어', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새우살', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('치즈', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('피클', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('삶은 달걀', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('케일', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('60g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바지락', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진파', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진청고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청주', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('미니 단호박', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소시지', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('맛술', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('백년초가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진소고기', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('떡볶이떡', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홍합', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('돼지등심', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('- 곁들임채소 : 어린잎(10g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('보리쌀', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다진 파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('가래떡', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('마른 표고버섯', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('저염 간', 1, '장');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('물엿', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('크렌베리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파마산치즈', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바지락살', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('노란 파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('알배추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('장어', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('슬라이스햄', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('망고', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('치커리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홍피망', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('옥수수', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('보리', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('와사비', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('게맛살', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('숙주', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('모짜렐라치즈', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('키위', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('목이버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('연어(훈제연어', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('사워크림', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소라', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('완두콩', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('현미', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('까나리액젓', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('돌나물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('관자', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('고추기름', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('노랑 파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('빨강 파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('고사리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('베이비채소', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('쌀밥', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('베이컨', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('발사믹식초', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('통삼겹', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청피망', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('새우젓', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('자숙새우', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소라살', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('백미', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('귀리', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('생 표고버섯', 9, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('월계수잎', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('수수', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('케첩', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('꼬치', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('200g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('당면', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('풋고추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('피클링스파이스', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('와인', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('고등어', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('묵은지', 7, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('배추', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('취나물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('곤드레나물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('유부', 7, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('가쓰오부시', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('사과식초', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('실파', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('빨강파프리카', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('호상요구르트', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('현미유', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('젓갈', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('건조미역줄기', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소주', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('불린쌀', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('요구르트', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('배춧잎', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('머스터드', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('캐슈넛', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('- 곁들임 : 어린잎(10g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('흑미', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오이피클', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('미숫가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('적채', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('은행', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('팥', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('50g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바질잎', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('대두유', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('사과즙', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('식빵', 8, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아몬드 슬라이스', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('달걀물', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('미림', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('250g)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('2인분 기준<br>', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('1인분 기준<br>', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바게트', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('다시마(5×5c', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('로메인', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파르메산 치즈', 6, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('스테비아', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('곤약', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('[ 2인분 ] 가지(1개)', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파프리카(빨강', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파프리카가루', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('흰후춧가루', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오레가노마른것', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바질마른것', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('깐연근', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('청피망다진것', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('토마토콩카세', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('홍피망다진것', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('후춧가루 적당량', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('블랙올리브', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('바질', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('도미살', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레몬주스', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('오렌지주스', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('아몬드슬라이스', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레몬제스트', 10, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('파슬리다진것', 2, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('레드어니언', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('물전분', 5, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('식물성기름', 1, 'ml');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('얼음', 1, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('멸치', 4, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('소고기(불고기용', 3, 'g');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('진간', 1, '장');
INSERT INTO Ingredient_Master (ingredient_name, category_id, base_unit) VALUES ('삼색파프리카', 1, 'g');
